public class ContractUploadConstants {
        
    public static final String IS_SUCCESS = 'isSuccess' ;
    public static final String MESSAGE = 'msg' ;
    public static final String JSON_STR = 'json' ;
    public static final String SUCCESS_MSG = 'Sucesso' ;
    public static final String HEADER_LIST_STR = 'headerList' ;
    public static final String INVALID_PARAMS_MSG = 'Parâmetros inválidos' ;

}