public with sharing class IntegrationConstants {
    public static final String RESERVATION_INC_METADATA = 'ElfaReservationINCAPI';
    public static final String RESERVATION_ALT_METADATA = 'ElfaReservationALTAPI';
    public static final String RESERVATION_FINANCIAL_BALANCE_ALT_METADATA = 'ElfaReservationFinancialBalance';
    public static final String RESERVATION_DEL_METADATA = 'ElfaReservationDelAPI';
    public static final String RESERVATION_POST_METADATA = 'ElfaReservationPost';
    public static final String HEADER_TYPE_CONTENT = 'Content-Type';
    public static final String HEADER_TYPE_CONTENT_JSON = 'application/json';
    public static final String AUTHORIZATION = 'Authorization';
    public static final String BASIC = 'Basic ';
    public static final Integer TIMEOUT = 120000;
    public static final String RESERVATION = 'Reserva';
    public static final String OUTBOUND = 'Outbound';
    public static final String STATUS_INTEGRATION_ERROR = 'Erro de integração';
    public static final String STATUS_INTEGRATION_ACTIVE = 'Ativa';
}
